deps_config := \
	config/contrib/gcc-test-suite.in \
	config/test_suite.in \
	config/comp_tools/make.in \
	config/versions/make.in \
	config/comp_tools/m4.in \
	config/versions/m4.in \
	config/comp_tools/libtool.in \
	config/versions/libtool.in \
	config/comp_tools/dtc.in \
	config/versions/dtc.in \
	config/comp_tools/bison.in \
	config/versions/bison.in \
	config/comp_tools/automake.in \
	config/versions/automake.in \
	config/comp_tools/autoconf.in \
	config/versions/autoconf.in \
	config/gen/comp_tools.in \
	config/comp_tools.in \
	config/comp_libs/zstd.in \
	config/versions/zstd.in \
	config/comp_libs/zlib.in \
	config/versions/zlib.in \
	config/comp_libs/picolibc.in \
	config/comp_libs/newlib-nano.in \
	config/versions/newlib-nano.in \
	config/comp_libs/ncurses.in \
	config/versions/ncurses.in \
	config/comp_libs/mpfr.in \
	config/versions/mpfr.in \
	config/comp_libs/mpc.in \
	config/versions/mpc.in \
	config/comp_libs/libiconv.in \
	config/versions/libiconv.in \
	config/comp_libs/libelf.in \
	config/versions/libelf.in \
	config/comp_libs/isl.in \
	config/versions/isl.in \
	config/comp_libs/gnuprumcu.in \
	config/versions/gnuprumcu.in \
	config/comp_libs/gmp.in \
	config/versions/gmp.in \
	config/comp_libs/gettext.in \
	config/versions/gettext.in \
	config/comp_libs/expat.in \
	config/versions/expat.in \
	config/comp_libs/cloog.in \
	config/versions/cloog.in \
	config/gen/comp_libs.in \
	config/comp_libs.in \
	config/debug/strace.in \
	config/versions/strace.in \
	config/debug/ltrace.in \
	config/versions/ltrace.in \
	config/debug/gdb.in.native \
	config/debug/gdb.in.cross \
	config/debug/gdb.in \
	config/versions/gdb.in \
	config/debug/duma.in \
	config/versions/duma.in \
	config/gen/debug.in \
	config/debug.in \
	config/linker/mold.in \
	config/versions/mold.in \
	config/gen/linker.in \
	config/linker.in \
	config/cc/gcc.in.mips \
	config/cc/gcc.in \
	config/versions/gcc.in \
	config/gen/cc.in \
	config/cc.in \
	config/libc/uClibc-ng.in \
	config/versions/uClibc-ng.in \
	config/libc/picolibc.in \
	config/versions/picolibc.in \
	config/libc/none.in \
	config/libc/newlib.in \
	config/versions/newlib.in \
	config/libc/musl.in \
	config/versions/musl.in \
	config/libc/moxiebox.in \
	config/versions/moxiebox.in \
	config/libc/mingw-w64.in \
	config/versions/mingw-w64.in \
	config/libc/glibc.in \
	config/versions/glibc.in \
	config/libc/avr-libc.in \
	config/versions/avr-libc.in \
	config/gen/libc.in \
	config/libc.in \
	config/versions/elf2flt.in \
	config/binutils/binutils.in \
	config/versions/binutils.in \
	config/gen/binutils.in \
	config/binutils.in \
	config/kernel/windows.in \
	config/kernel/linux.in \
	config/versions/linux.in \
	config/kernel/bare-metal.in \
	config/gen/kernel.in \
	config/kernel.in \
	config/toolchain.in \
	config/arch/xtensa.in \
	config/arch/x86.in \
	config/arch/tricore.in \
	config/arch/sparc.in \
	config/arch/sh.in \
	config/arch/s390.in \
	config/arch/rx.in \
	config/arch/riscv.in \
	config/arch/pru.in \
	config/arch/powerpc.in \
	config/arch/parisc.in \
	config/arch/openrisc.in \
	config/arch/nios2.in \
	config/arch/msp430.in \
	config/arch/moxie.in \
	config/arch/mips.in \
	config/arch/microblaze.in \
	config/arch/m68k.in \
	config/arch/loongarch.in \
	config/arch/lm32.in \
	config/arch/c6x.in \
	config/arch/bpf.in \
	config/arch/avr.in \
	config/arch/arm.in \
	config/arch/arc.in \
	config/arch/alpha.in \
	config/gen/arch.in \
	config/target.in \
	config/global/logging.in \
	config/global/build-behave.in \
	config/global/extract.in \
	config/global/download.in \
	config/global/paths.in \
	config/global/ct-behave.in \
	config/global.in \
	config/configure.in \
	config/config_utils.in \
	/usr/share/crosstool-ng/config/config.in

include/config/auto.conf: \
	$(deps_config)

ifneq "$(CT_VERSION)" "1.28.0"
include/config/auto.conf: FORCE
endif
ifneq "$(CT_VCHECK)" ""
include/config/auto.conf: FORCE
endif
ifneq "$(CT_CONFIG_VERSION_CURRENT)" "4"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
